// Curated list of BGG categories and mechanics that the model was trained on.
// These represent the most common/impactful values found in the processed dataset.

export const CATEGORIES = [
  "Abstract Strategy",
  "Adventure",
  "Age of Reason",
  "American Civil War",
  "American Indian Wars",
  "American Revolutionary War",
  "American West",
  "Ancient",
  "Animals",
  "Arabian",
  "Bluffing",
  "Card Game",
  "Children's Game",
  "City Building",
  "Civil War",
  "Civilization",
  "Collectible Components",
  "Comic Book / Strip",
  "Deduction",
  "Dice",
  "Economic",
  "Educational",
  "Electronic",
  "Environmental",
  "Exploration",
  "Fantasy",
  "Fighting",
  "Horror",
  "Humor",
  "Industry / Manufacturing",
  "Mafia",
  "Math",
  "Mature / Adult",
  "Maze",
  "Medical",
  "Medieval",
  "Memory",
  "Miniatures",
  "Movies / TV / Radio theme",
  "Murder / Mystery",
  "Mythology",
  "Napoleonic",
  "Nautical",
  "Negotiation",
  "Novel-based",
  "Number",
  "Party Game",
  "Pike and Shot",
  "Pirates",
  "Political",
  "Post-Napoleonic",
  "Prehistoric",
  "Print & Play",
  "Puzzle",
  "Racing",
  "Real-time",
  "Religious",
  "Renaissance",
  "Science Fiction",
  "Space Exploration",
  "Spies/Secret Agents",
  "Sports",
  "Territory Building",
  "Trains",
  "Transportation",
  "Travel",
  "Trivia",
  "Video Game Theme",
  "Wargame",
  "Word Game",
  "World War I",
  "World War II",
  "Zombies",
];

export const MECHANICS = [
  "Action Points",
  "Action Queue",
  "Action Retrieval",
  "Area Control",
  "Area Majority / Influence",
  "Area Movement",
  "Auction / Bidding",
  "Bag and Pool Building",
  "Betting and Bluffing",
  "Campaign / Battle Card Driven",
  "Card Drafting",
  "Card Play Conflict Resolution",
  "Catch the Leader",
  "Chit-Pull System",
  "Closed Drafting",
  "Closed Economy Auction",
  "Commodity Speculation",
  "Communication Limits",
  "Connections",
  "Cooperative Game",
  "Deduction",
  "Deck Construction",
  "Dice Rolling",
  "Different Worker Types",
  "Drafting",
  "Drawing",
  "Elapsed Real Time Ending",
  "Enclosure",
  "End Game Bonuses",
  "Events",
  "Hand Management",
  "Hexagon Grid",
  "Hidden Movement",
  "Hidden Roles",
  "Income",
  "Layering",
  "Legacy Game",
  "Line Drawing",
  "Loans",
  "Map Addition",
  "Map Deformation",
  "Map Reduction",
  "Market",
  "Matching",
  "Memory",
  "Modular Board",
  "Movement Points",
  "Moving Multiple Units",
  "Multi-Use Cards",
  "Negotiation",
  "Network and Route Building",
  "Open Drafting",
  "Paper-and-Pencil",
  "Pattern Building",
  "Pattern Recognition",
  "Pick-up and Deliver",
  "Player Elimination",
  "Point to Point Movement",
  "Programmed Movement",
  "Push Your Luck",
  "Racing",
  "Resource to Move",
  "Role Playing",
  "Roll / Spin and Move",
  "Secret Unit Deployment",
  "Semi-Cooperative Game",
  "Set Collection",
  "Simulation",
  "Simultaneous Action Selection",
  "Singing",
  "Slide / Push",
  "Solo / Solitaire Game",
  "Stacking and Balancing",
  "Stock Holding",
  "Storytelling",
  "Sudden Death Ending",
  "Tile Placement",
  "Trading",
  "Trick-taking",
  "Variable Phase Order",
  "Variable Player Powers",
  "Variable Set-up",
  "Victory Points as a Resource",
  "Voting",
  "Worker Placement",
  "Worker Placement with Dice Workers",
];

export interface Preset {
  name: string;
  emoji: string;
  description: string;
  categories: string[];
  mechanics: string[];
}

export const PRESETS: Preset[] = [
  {
    name: "Euro Strategy",
    emoji: "🏛️",
    description: "Worker placement economy game",
    categories: ["Economic", "Territory Building", "City Building"],
    mechanics: [
      "Worker Placement",
      "Resource to Move",
      "Hand Management",
      "End Game Bonuses",
    ],
  },
  {
    name: "Co-op Dungeon",
    emoji: "⚔️",
    description: "Fantasy co-op adventure",
    categories: ["Fantasy", "Adventure", "Fighting"],
    mechanics: [
      "Cooperative Game",
      "Dice Rolling",
      "Hand Management",
      "Variable Player Powers",
    ],
  },
  {
    name: "Deck Builder",
    emoji: "🃏",
    description: "Competitive card drafting",
    categories: ["Card Game"],
    mechanics: [
      "Deck Construction",
      "Card Drafting",
      "Hand Management",
      "Set Collection",
    ],
  },
  {
    name: "Sci-Fi Wargame",
    emoji: "🚀",
    description: "Space area-control conflict",
    categories: ["Science Fiction", "Space Exploration", "Wargame"],
    mechanics: [
      "Area Control",
      "Hexagon Grid",
      "Dice Rolling",
      "Variable Player Powers",
      "Area Movement",
    ],
  },
  {
    name: "Party Game",
    emoji: "🎉",
    description: "Fast social deduction",
    categories: ["Party Game", "Humor", "Bluffing"],
    mechanics: [
      "Hidden Roles",
      "Voting",
      "Simultaneous Action Selection",
      "Betting and Bluffing",
    ],
  },
  {
    name: "Tile Puzzle",
    emoji: "🧩",
    description: "Abstract spatial challenge",
    categories: ["Abstract Strategy", "Puzzle"],
    mechanics: [
      "Tile Placement",
      "Pattern Building",
      "Area Control",
      "Modular Board",
    ],
  },
];
